spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kduck?useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: liuhg
    password: gang317
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
logging:
  level:
    root: error
    cn.kduck: info

kduck:
  showSql:
    enabled: true
  resource:
    enabled: true
  security:
    ignored: /welcome.html
    loginPage: /index.html

server:
  port: 8000