spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/k-duck?useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: liuhg
    password: gang317
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
#  rabbitmq:
#    host: 192.168.9.110
#    port: 33274
#    username: gtiles
#    password: Klx1234!
#    virtual-host: dev-boe
logging:
  level:
    root: error
    cn.kduck: info

kduck:
  showSql:
    enabled: false
  resource:
    enabled: true
  websocket:
    enabled: true
  security:
    ignored: /welcome.html,/*.xml
    loginPage: /index.html
  flow:
    baseUrl: http://127.0.0.1:8088/kduck-engine-rest

server:
  port: 8000